# Generated by Django 3.1.5 on 2026-03-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central_mess', '0003_auto_20250209_1736'),
        ('central_mess', '0002_auto_20241020_1126'),
    ]

    operations = [
    ]
